config/routes.rb
Rails.application.routes.draw do
  resources :categorias
  root to: 'visitors#index'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	has_many :filhos, class_name: "Categoria", foreign_key: "pai_id"
	belongs_to :pai, class_name: "Categoria"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria was successfully created.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: 'Categoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to categorias_url, notice: 'Categoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:nome, :pai_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/categorias/_form.html.haml
= simple_form_for(@categoria) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.association :pai, label_method: :nome, value_method: :id

  .form-actions
    = f.submit "Salvar"

app/views/categorias/edit.html.haml
%h1 Editing categoria

= render 'form'

= link_to 'Show', @categoria
\|
= link_to 'Back', categorias_path

app/views/categorias/index.html.haml
%h1 Listing categorias

%table
  %thead
    %tr
      %th Nome
      %th Pai
      %th
      %th
      %th

  %tbody
    - @categorias.each do |categoria|
      %tr
        %td= categoria.nome
        %td= categoria.pai.nome if !categoria.pai.nil?
        %td= link_to 'Show', categoria
        %td= link_to 'Edit', edit_categoria_path(categoria)
        %td= link_to 'Destroy', categoria, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Categoria', new_categoria_path

app/views/categorias/new.html.haml
%h1 New categoria

= render 'form'

= link_to 'Back', categorias_path

app/views/categorias/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @categoria.nome
%p
  %b Pai:
  = @categoria.pai.nome if !@categoria.pai.nil?

= link_to 'Edit', edit_categoria_path(@categoria)
\|
= link_to 'Back', categorias_path

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<ul>
  <li><%= link_to 'Categorias',categorias_path %></li>
  
</ul>